// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ed2kGlobal': string;
  'kad': string;
  'torrent': string;
  'unknown': string;
  'usenet': string;
}
export const cssExports: CssExports;
export default cssExports;
